file:
  readPath: C:\Users\pkumar\IMPORTANT AND ADVANCED TOPICS\SF\Read
  movedPath: C:\Users\pkumar\IMPORTANT AND ADVANCED TOPICS\SF\Moved
  writePath: C:\Users\pkumar\IMPORTANT AND ADVANCED TOPICS\SF\Write